package org.agmas.noellesroles.mixin.roles.executioner;

import dev.doctor4t.trainmurdermystery.cca.GameWorldComponent;
import dev.doctor4t.trainmurdermystery.cca.PlayerShopComponent;
import dev.doctor4t.trainmurdermystery.game.GameFunctions;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.player.Player;
import org.agmas.noellesroles.role.ModRoles;
import org.agmas.noellesroles.roles.executioner.ExecutionerPlayerComponent;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import java.util.UUID;

@Mixin(GameFunctions.class)
public class ExecutionerConfirmMixin {
    @Inject(method = "killPlayer(Lnet/minecraft/world/entity/player/Player;ZLnet/minecraft/world/entity/player/Player;Lnet/minecraft/resources/ResourceLocation;)V", at = @At("HEAD"),cancellable = true)
    private static void executionerConfirm(Player victim, boolean spawnBody, Player killer, ResourceLocation identifier, CallbackInfo ci) {
        final var world = victim.level();
        if (world==null)return;
        GameWorldComponent gameWorldComponent = GameWorldComponent.KEY.get(world);
        if (gameWorldComponent==null)return;


        for (UUID uuid : gameWorldComponent.getAllWithRole(ModRoles.EXECUTIONER)) {
            Player executioner = world.getPlayerByUUID(uuid);
            if (executioner == null) continue;
//            boolean invalidKill = false;
//            if (killer != null) {
//                if (gameWorldComponent.getRole(killer).canUseKiller()) invalidKill = true;
//            }
            ExecutionerPlayerComponent executionerPlayerComponent = ExecutionerPlayerComponent.KEY.get(executioner);
            PlayerShopComponent playerShopComponent = (PlayerShopComponent) PlayerShopComponent.KEY.get(executioner);
            if (executionerPlayerComponent.target != null && executionerPlayerComponent.target.equals(victim.getUUID()) ) {
                executionerPlayerComponent.assignRandomTarget();
//                ArrayList<Role> shuffledKillerRoles = new ArrayList<>(TMMRoles.ROLES);
//                shuffledKillerRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || !role.canUseKiller() || HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().getPath()));
//                if (shuffledKillerRoles.isEmpty()) shuffledKillerRoles.add(TMMRoles.KILLER);
//                Collections.shuffle(shuffledKillerRoles);

//                gameWorldComponent.addRole(executioner,shuffledKillerRoles.getFirst());
//                ModdedRoleAssigned.EVENT.invoker().assignModdedRole(executioner,shuffledKillerRoles.getFirst());
                if (killer!=null&& killer.getUUID().equals(uuid)){
                    playerShopComponent.setBalance(playerShopComponent.balance -25);

                }else {
                    playerShopComponent.setBalance(playerShopComponent.balance + 50);
                }
                 executionerPlayerComponent.sync();
                playerShopComponent.sync();
//                if (Harpymodloader.VANNILA_ROLES.contains(gameWorldComponent.getRole(executioner))) {
//                    ServerPlayNetworking.send((ServerPlayerEntity) executioner, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(TMMRoles.KILLER), gameWorldComponent.getAllKillerTeamPlayers().size(), 0));
//                } else {
//                    ServerPlayNetworking.send((ServerPlayerEntity) executioner, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(gameWorldComponent.getRole(executioner))), gameWorldComponent.getAllKillerTeamPlayers().size(), 0));
//                }
            }
        }
        if (killer==null)return;
        final var role = gameWorldComponent.getRole(killer);
        if (role== null)return;
        if (killer!=null) {
            if (victim!=null) {
                if (role.getIdentifier().equals(ModRoles.EXECUTIONER_ID)) {

                    if (!ExecutionerPlayerComponent.KEY.get(killer).target.equals(victim.getUUID())) {
                        ci.cancel();
                    }
                }
            }else {
                return;
            }
        }else {
            return;
        }

    }
}