package org.agmas.noellesroles.mixin.roles.executioner;

import dev.doctor4t.trainmurdermystery.cca.GameWorldComponent;
import dev.doctor4t.trainmurdermystery.cca.PlayerShopComponent;
import dev.doctor4t.trainmurdermystery.game.GameFunctions;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.util.Identifier;
import org.agmas.noellesroles.role.ModRoles;
import org.agmas.noellesroles.roles.executioner.ExecutionerPlayerComponent;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import java.util.UUID;

@Mixin(GameFunctions.class)
public class ExecutionerConfirmMixin {
    @Inject(method = "killPlayer(Lnet/minecraft/entity/player/PlayerEntity;ZLnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/util/Identifier;)V", at = @At("HEAD"))
    private static void executionerConfirm(PlayerEntity victim, boolean spawnBody, PlayerEntity killer, Identifier identifier, CallbackInfo ci) {
        final var world = victim.getWorld();
        if (world==null)return;
        GameWorldComponent gameWorldComponent = GameWorldComponent.KEY.get(world);
        final var role = gameWorldComponent.getRole(killer);

        if (gameWorldComponent==null)return;
        for (UUID uuid : gameWorldComponent.getAllWithRole(ModRoles.EXECUTIONER)) {
            PlayerEntity executioner = world.getPlayerByUuid(uuid);
            if (executioner == null) continue;
            boolean invalidKill = false;
            if (killer != null) {
                if (role.canUseKiller()) invalidKill = true;
            }
            ExecutionerPlayerComponent executionerPlayerComponent = ExecutionerPlayerComponent.KEY.get(executioner);
            PlayerShopComponent playerShopComponent = (PlayerShopComponent) PlayerShopComponent.KEY.get(executioner);
            if (executionerPlayerComponent.target != null && executionerPlayerComponent.target.equals(victim.getUuid()) && !invalidKill) {
                executionerPlayerComponent.won = true;
//                ArrayList<Role> shuffledKillerRoles = new ArrayList<>(TMMRoles.ROLES);
//                shuffledKillerRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || !role.canUseKiller() || HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().getPath()));
//                if (shuffledKillerRoles.isEmpty()) shuffledKillerRoles.add(TMMRoles.KILLER);
//                Collections.shuffle(shuffledKillerRoles);

//                gameWorldComponent.addRole(executioner,shuffledKillerRoles.getFirst());
//                ModdedRoleAssigned.EVENT.invoker().assignModdedRole(executioner,shuffledKillerRoles.getFirst());
                playerShopComponent.setBalance(playerShopComponent.balance + 50); // 增加余额而不是设置为固定值
//                if (Harpymodloader.VANNILA_ROLES.contains(gameWorldComponent.getRole(executioner))) {
//                    ServerPlayNetworking.send((ServerPlayerEntity) executioner, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(TMMRoles.KILLER), gameWorldComponent.getAllKillerTeamPlayers().size(), 0));
//                } else {
//                    ServerPlayNetworking.send((ServerPlayerEntity) executioner, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(gameWorldComponent.getRole(executioner))), gameWorldComponent.getAllKillerTeamPlayers().size(), 0));
//                }
            }
        }

        if (role==null)return;
        if (killer!=null) {
            if (victim!=null) {
                if (role.getIdentifier().equals(ModRoles.EXECUTIONER_ID)) {

                    if (!ExecutionerPlayerComponent.KEY.get(killer).target.equals(victim.getUuid())) {
                        ci.cancel();
                    }
                }
            }else {
                return;
            }
        }else {
            return;
        }

    }
}